/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "unity.h"
#include "getHandlersForReadDataById.h"
#include "mock_diagnostic_cfg.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_getHandlersForReadDataById_ValidDID_F308(void);
extern void test_getHandlersForReadDataById_InvalidDID(void);
extern void test_getHandlersForReadDataById_MultipleInvalidDIDs(void);
extern void test_getHandlersForReadDataById_ValidDID_HandlerReturnsError(void);
extern void test_getHandlersForReadDataById_ErrorCodePassedToHandler(void);
extern void test_getHandlersForReadDataById_OutputBufferPassedToHandler(void);
extern void test_getHandlersForReadDataById_BufferSizePointerPassedToHandler(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_diagnostic_cfg_Init();
}
static void CMock_Verify(void)
{
  mock_diagnostic_cfg_Verify();
}
static void CMock_Destroy(void)
{
  mock_diagnostic_cfg_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_getHandlersForReadDataById.c");
  run_test(test_getHandlersForReadDataById_ValidDID_F308, "test_getHandlersForReadDataById_ValidDID_F308", 19);
  run_test(test_getHandlersForReadDataById_InvalidDID, "test_getHandlersForReadDataById_InvalidDID", 48);
  run_test(test_getHandlersForReadDataById_MultipleInvalidDIDs, "test_getHandlersForReadDataById_MultipleInvalidDIDs", 77);
  run_test(test_getHandlersForReadDataById_ValidDID_HandlerReturnsError, "test_getHandlersForReadDataById_ValidDID_HandlerReturnsError", 103);
  run_test(test_getHandlersForReadDataById_ErrorCodePassedToHandler, "test_getHandlersForReadDataById_ErrorCodePassedToHandler", 129);
  run_test(test_getHandlersForReadDataById_OutputBufferPassedToHandler, "test_getHandlersForReadDataById_OutputBufferPassedToHandler", 150);
  run_test(test_getHandlersForReadDataById_BufferSizePointerPassedToHandler, "test_getHandlersForReadDataById_BufferSizePointerPassedToHandler", 171);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
