/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_diagnostic_cfg.h"

static const char* CMockString_RdbiVhitOverVoltageFaultDiag_ = "RdbiVhitOverVoltageFaultDiag_";
static const char* CMockString_SubfunctionRequestOutOfRange_ = "SubfunctionRequestOutOfRange_";
static const char* CMockString_checkCurrentNad = "checkCurrentNad";
static const char* CMockString_checkMsgDataLength = "checkMsgDataLength";
static const char* CMockString_currentNad = "currentNad";
static const char* CMockString_dataLength = "dataLength";
static const char* CMockString_errCode_pu8 = "errCode_pu8";
static const char* CMockString_output_pu8 = "output_pu8";
static const char* CMockString_result = "result";
static const char* CMockString_size_pu8 = "size_pu8";

typedef struct _CMOCK_checkCurrentNad_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint8 Expected_currentNad;
  Std_ReturnType* Expected_result;

} CMOCK_checkCurrentNad_CALL_INSTANCE;

typedef struct _CMOCK_checkMsgDataLength_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint16_t Expected_dataLength;
  Std_ReturnType* Expected_result;

} CMOCK_checkMsgDataLength_CALL_INSTANCE;

typedef struct _CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Std_ReturnType ReturnVal;
  int CallOrder;
  uint8* Expected_output_pu8;
  uint8* Expected_size_pu8;
  uint8* Expected_errCode_pu8;

} CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE;

typedef struct _CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Std_ReturnType ReturnVal;
  int CallOrder;
  uint8* Expected_output_pu8;
  uint8* Expected_size_pu8;
  uint8* Expected_errCode_pu8;

} CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE;

static struct mock_diagnostic_cfgInstance
{
  char checkCurrentNad_IgnoreBool;
  char checkCurrentNad_CallbackBool;
  CMOCK_checkCurrentNad_CALLBACK checkCurrentNad_CallbackFunctionPointer;
  int checkCurrentNad_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE checkCurrentNad_CallInstance;
  char checkMsgDataLength_IgnoreBool;
  char checkMsgDataLength_CallbackBool;
  CMOCK_checkMsgDataLength_CALLBACK checkMsgDataLength_CallbackFunctionPointer;
  int checkMsgDataLength_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE checkMsgDataLength_CallInstance;
  char RdbiVhitOverVoltageFaultDiag__IgnoreBool;
  Std_ReturnType RdbiVhitOverVoltageFaultDiag__FinalReturn;
  char RdbiVhitOverVoltageFaultDiag__CallbackBool;
  CMOCK_RdbiVhitOverVoltageFaultDiag__CALLBACK RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer;
  int RdbiVhitOverVoltageFaultDiag__CallbackCalls;
  CMOCK_MEM_INDEX_TYPE RdbiVhitOverVoltageFaultDiag__CallInstance;
  char SubfunctionRequestOutOfRange__IgnoreBool;
  Std_ReturnType SubfunctionRequestOutOfRange__FinalReturn;
  char SubfunctionRequestOutOfRange__CallbackBool;
  CMOCK_SubfunctionRequestOutOfRange__CALLBACK SubfunctionRequestOutOfRange__CallbackFunctionPointer;
  int SubfunctionRequestOutOfRange__CallbackCalls;
  CMOCK_MEM_INDEX_TYPE SubfunctionRequestOutOfRange__CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_diagnostic_cfg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.checkCurrentNad_CallInstance;
  if (Mock.checkCurrentNad_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_checkCurrentNad);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.checkCurrentNad_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.checkMsgDataLength_CallInstance;
  if (Mock.checkMsgDataLength_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_checkMsgDataLength);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.checkMsgDataLength_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.RdbiVhitOverVoltageFaultDiag__CallInstance;
  if (Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_RdbiVhitOverVoltageFaultDiag_);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.SubfunctionRequestOutOfRange__CallInstance;
  if (Mock.SubfunctionRequestOutOfRange__IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_SubfunctionRequestOutOfRange_);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_diagnostic_cfg_Init(void)
{
  mock_diagnostic_cfg_Destroy();
}

void mock_diagnostic_cfg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void checkCurrentNad(uint8 currentNad, Std_ReturnType* result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_checkCurrentNad);
  cmock_call_instance = (CMOCK_checkCurrentNad_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.checkCurrentNad_CallInstance);
  Mock.checkCurrentNad_CallInstance = CMock_Guts_MemNext(Mock.checkCurrentNad_CallInstance);
  if (Mock.checkCurrentNad_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.checkCurrentNad_CallbackBool &&
      Mock.checkCurrentNad_CallbackFunctionPointer != NULL)
  {
    Mock.checkCurrentNad_CallbackFunctionPointer(currentNad, result, Mock.checkCurrentNad_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_checkCurrentNad,CMockString_currentNad);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_currentNad, currentNad, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_checkCurrentNad,CMockString_result);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_result), (void*)(result), sizeof(Std_ReturnType), cmock_line, CMockStringMismatch);
  }
  if (Mock.checkCurrentNad_CallbackFunctionPointer != NULL)
  {
    Mock.checkCurrentNad_CallbackFunctionPointer(currentNad, result, Mock.checkCurrentNad_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_checkCurrentNad(CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance, uint8 currentNad, Std_ReturnType* result);
void CMockExpectParameters_checkCurrentNad(CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance, uint8 currentNad, Std_ReturnType* result)
{
  cmock_call_instance->Expected_currentNad = currentNad;
  cmock_call_instance->Expected_result = result;
}

void checkCurrentNad_CMockIgnore(void)
{
  Mock.checkCurrentNad_IgnoreBool = (char)1;
}

void checkCurrentNad_CMockStopIgnore(void)
{
  Mock.checkCurrentNad_IgnoreBool = (char)0;
}

void checkCurrentNad_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8 currentNad, Std_ReturnType* result)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_checkCurrentNad_CALL_INSTANCE));
  CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance = (CMOCK_checkCurrentNad_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.checkCurrentNad_CallInstance = CMock_Guts_MemChain(Mock.checkCurrentNad_CallInstance, cmock_guts_index);
  Mock.checkCurrentNad_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_checkCurrentNad(cmock_call_instance, currentNad, result);
}

void checkCurrentNad_AddCallback(CMOCK_checkCurrentNad_CALLBACK Callback)
{
  Mock.checkCurrentNad_IgnoreBool = (char)0;
  Mock.checkCurrentNad_CallbackBool = (char)1;
  Mock.checkCurrentNad_CallbackFunctionPointer = Callback;
}

void checkCurrentNad_Stub(CMOCK_checkCurrentNad_CALLBACK Callback)
{
  Mock.checkCurrentNad_IgnoreBool = (char)0;
  Mock.checkCurrentNad_CallbackBool = (char)0;
  Mock.checkCurrentNad_CallbackFunctionPointer = Callback;
}

void checkMsgDataLength(uint16_t dataLength, Std_ReturnType* result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_checkMsgDataLength);
  cmock_call_instance = (CMOCK_checkMsgDataLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.checkMsgDataLength_CallInstance);
  Mock.checkMsgDataLength_CallInstance = CMock_Guts_MemNext(Mock.checkMsgDataLength_CallInstance);
  if (Mock.checkMsgDataLength_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.checkMsgDataLength_CallbackBool &&
      Mock.checkMsgDataLength_CallbackFunctionPointer != NULL)
  {
    Mock.checkMsgDataLength_CallbackFunctionPointer(dataLength, result, Mock.checkMsgDataLength_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_checkMsgDataLength,CMockString_dataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_dataLength, dataLength, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_checkMsgDataLength,CMockString_result);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_result), (void*)(result), sizeof(Std_ReturnType), cmock_line, CMockStringMismatch);
  }
  if (Mock.checkMsgDataLength_CallbackFunctionPointer != NULL)
  {
    Mock.checkMsgDataLength_CallbackFunctionPointer(dataLength, result, Mock.checkMsgDataLength_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_checkMsgDataLength(CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance, uint16_t dataLength, Std_ReturnType* result);
void CMockExpectParameters_checkMsgDataLength(CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance, uint16_t dataLength, Std_ReturnType* result)
{
  cmock_call_instance->Expected_dataLength = dataLength;
  cmock_call_instance->Expected_result = result;
}

void checkMsgDataLength_CMockIgnore(void)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)1;
}

void checkMsgDataLength_CMockStopIgnore(void)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
}

void checkMsgDataLength_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t dataLength, Std_ReturnType* result)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_checkMsgDataLength_CALL_INSTANCE));
  CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance = (CMOCK_checkMsgDataLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.checkMsgDataLength_CallInstance = CMock_Guts_MemChain(Mock.checkMsgDataLength_CallInstance, cmock_guts_index);
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_checkMsgDataLength(cmock_call_instance, dataLength, result);
}

void checkMsgDataLength_AddCallback(CMOCK_checkMsgDataLength_CALLBACK Callback)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
  Mock.checkMsgDataLength_CallbackBool = (char)1;
  Mock.checkMsgDataLength_CallbackFunctionPointer = Callback;
}

void checkMsgDataLength_Stub(CMOCK_checkMsgDataLength_CALLBACK Callback)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
  Mock.checkMsgDataLength_CallbackBool = (char)0;
  Mock.checkMsgDataLength_CallbackFunctionPointer = Callback;
}

Std_ReturnType RdbiVhitOverVoltageFaultDiag_(uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_RdbiVhitOverVoltageFaultDiag_);
  cmock_call_instance = (CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.RdbiVhitOverVoltageFaultDiag__CallInstance);
  Mock.RdbiVhitOverVoltageFaultDiag__CallInstance = CMock_Guts_MemNext(Mock.RdbiVhitOverVoltageFaultDiag__CallInstance);
  if (Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.RdbiVhitOverVoltageFaultDiag__FinalReturn;
    memcpy((void*)(&Mock.RdbiVhitOverVoltageFaultDiag__FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(Std_ReturnType[sizeof(cmock_call_instance->ReturnVal) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.RdbiVhitOverVoltageFaultDiag__CallbackBool &&
      Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer != NULL)
  {
    Std_ReturnType cmock_cb_ret = Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer(output_pu8, size_pu8, errCode_pu8, Mock.RdbiVhitOverVoltageFaultDiag__CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_RdbiVhitOverVoltageFaultDiag_,CMockString_output_pu8);
    if (cmock_call_instance->Expected_output_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(output_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_output_pu8, output_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_RdbiVhitOverVoltageFaultDiag_,CMockString_size_pu8);
    if (cmock_call_instance->Expected_size_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(size_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_size_pu8, size_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_RdbiVhitOverVoltageFaultDiag_,CMockString_errCode_pu8);
    if (cmock_call_instance->Expected_errCode_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(errCode_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_errCode_pu8, errCode_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer(output_pu8, size_pu8, errCode_pu8, Mock.RdbiVhitOverVoltageFaultDiag__CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_RdbiVhitOverVoltageFaultDiag_(CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE* cmock_call_instance, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8);
void CMockExpectParameters_RdbiVhitOverVoltageFaultDiag_(CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE* cmock_call_instance, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8)
{
  cmock_call_instance->Expected_output_pu8 = output_pu8;
  cmock_call_instance->Expected_size_pu8 = size_pu8;
  cmock_call_instance->Expected_errCode_pu8 = errCode_pu8;
}

void RdbiVhitOverVoltageFaultDiag__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE));
  CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE* cmock_call_instance = (CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.RdbiVhitOverVoltageFaultDiag__CallInstance = CMock_Guts_MemChain(Mock.RdbiVhitOverVoltageFaultDiag__CallInstance, cmock_guts_index);
  Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool = (char)1;
}

void RdbiVhitOverVoltageFaultDiag__CMockStopIgnore(void)
{
  if(Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool)
    Mock.RdbiVhitOverVoltageFaultDiag__CallInstance = CMock_Guts_MemNext(Mock.RdbiVhitOverVoltageFaultDiag__CallInstance);
  Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool = (char)0;
}

void RdbiVhitOverVoltageFaultDiag__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE));
  CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE* cmock_call_instance = (CMOCK_RdbiVhitOverVoltageFaultDiag__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.RdbiVhitOverVoltageFaultDiag__CallInstance = CMock_Guts_MemChain(Mock.RdbiVhitOverVoltageFaultDiag__CallInstance, cmock_guts_index);
  Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_RdbiVhitOverVoltageFaultDiag_(cmock_call_instance, output_pu8, size_pu8, errCode_pu8);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(Std_ReturnType[sizeof(cmock_to_return) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
}

void RdbiVhitOverVoltageFaultDiag__AddCallback(CMOCK_RdbiVhitOverVoltageFaultDiag__CALLBACK Callback)
{
  Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool = (char)0;
  Mock.RdbiVhitOverVoltageFaultDiag__CallbackBool = (char)1;
  Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer = Callback;
}

void RdbiVhitOverVoltageFaultDiag__Stub(CMOCK_RdbiVhitOverVoltageFaultDiag__CALLBACK Callback)
{
  Mock.RdbiVhitOverVoltageFaultDiag__IgnoreBool = (char)0;
  Mock.RdbiVhitOverVoltageFaultDiag__CallbackBool = (char)0;
  Mock.RdbiVhitOverVoltageFaultDiag__CallbackFunctionPointer = Callback;
}

Std_ReturnType SubfunctionRequestOutOfRange_(uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SubfunctionRequestOutOfRange_);
  cmock_call_instance = (CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SubfunctionRequestOutOfRange__CallInstance);
  Mock.SubfunctionRequestOutOfRange__CallInstance = CMock_Guts_MemNext(Mock.SubfunctionRequestOutOfRange__CallInstance);
  if (Mock.SubfunctionRequestOutOfRange__IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SubfunctionRequestOutOfRange__FinalReturn;
    memcpy((void*)(&Mock.SubfunctionRequestOutOfRange__FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(Std_ReturnType[sizeof(cmock_call_instance->ReturnVal) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.SubfunctionRequestOutOfRange__CallbackBool &&
      Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer != NULL)
  {
    Std_ReturnType cmock_cb_ret = Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer(output_pu8, size_pu8, errCode_pu8, Mock.SubfunctionRequestOutOfRange__CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_SubfunctionRequestOutOfRange_,CMockString_output_pu8);
    if (cmock_call_instance->Expected_output_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(output_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_output_pu8, output_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_SubfunctionRequestOutOfRange_,CMockString_size_pu8);
    if (cmock_call_instance->Expected_size_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(size_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_size_pu8, size_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_SubfunctionRequestOutOfRange_,CMockString_errCode_pu8);
    if (cmock_call_instance->Expected_errCode_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(errCode_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_errCode_pu8, errCode_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer(output_pu8, size_pu8, errCode_pu8, Mock.SubfunctionRequestOutOfRange__CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SubfunctionRequestOutOfRange_(CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE* cmock_call_instance, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8);
void CMockExpectParameters_SubfunctionRequestOutOfRange_(CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE* cmock_call_instance, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8)
{
  cmock_call_instance->Expected_output_pu8 = output_pu8;
  cmock_call_instance->Expected_size_pu8 = size_pu8;
  cmock_call_instance->Expected_errCode_pu8 = errCode_pu8;
}

void SubfunctionRequestOutOfRange__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE));
  CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE* cmock_call_instance = (CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SubfunctionRequestOutOfRange__CallInstance = CMock_Guts_MemChain(Mock.SubfunctionRequestOutOfRange__CallInstance, cmock_guts_index);
  Mock.SubfunctionRequestOutOfRange__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SubfunctionRequestOutOfRange__IgnoreBool = (char)1;
}

void SubfunctionRequestOutOfRange__CMockStopIgnore(void)
{
  if(Mock.SubfunctionRequestOutOfRange__IgnoreBool)
    Mock.SubfunctionRequestOutOfRange__CallInstance = CMock_Guts_MemNext(Mock.SubfunctionRequestOutOfRange__CallInstance);
  Mock.SubfunctionRequestOutOfRange__IgnoreBool = (char)0;
}

void SubfunctionRequestOutOfRange__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE));
  CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE* cmock_call_instance = (CMOCK_SubfunctionRequestOutOfRange__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SubfunctionRequestOutOfRange__CallInstance = CMock_Guts_MemChain(Mock.SubfunctionRequestOutOfRange__CallInstance, cmock_guts_index);
  Mock.SubfunctionRequestOutOfRange__IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_SubfunctionRequestOutOfRange_(cmock_call_instance, output_pu8, size_pu8, errCode_pu8);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(Std_ReturnType[sizeof(cmock_to_return) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
}

void SubfunctionRequestOutOfRange__AddCallback(CMOCK_SubfunctionRequestOutOfRange__CALLBACK Callback)
{
  Mock.SubfunctionRequestOutOfRange__IgnoreBool = (char)0;
  Mock.SubfunctionRequestOutOfRange__CallbackBool = (char)1;
  Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer = Callback;
}

void SubfunctionRequestOutOfRange__Stub(CMOCK_SubfunctionRequestOutOfRange__CALLBACK Callback)
{
  Mock.SubfunctionRequestOutOfRange__IgnoreBool = (char)0;
  Mock.SubfunctionRequestOutOfRange__CallbackBool = (char)0;
  Mock.SubfunctionRequestOutOfRange__CallbackFunctionPointer = Callback;
}

