/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_DIAGNOSTIC_CFG_H
#define _MOCK_DIAGNOSTIC_CFG_H

#include "unity.h"
#include "diagnostic_cfg.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_diagnostic_cfg_Init(void);
void mock_diagnostic_cfg_Destroy(void);
void mock_diagnostic_cfg_Verify(void);




#define checkCurrentNad_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("checkCurrentNad requires _Ignore (not AndReturn)");
#define checkCurrentNad_Ignore() checkCurrentNad_CMockIgnore()
void checkCurrentNad_CMockIgnore(void);
#define checkCurrentNad_StopIgnore() checkCurrentNad_CMockStopIgnore()
void checkCurrentNad_CMockStopIgnore(void);
#define checkCurrentNad_ExpectAndReturn(currentNad, result, cmock_retval) TEST_FAIL_MESSAGE("checkCurrentNad requires _Expect (not AndReturn)");
#define checkCurrentNad_Expect(currentNad, result) checkCurrentNad_CMockExpect(__LINE__, currentNad, result)
void checkCurrentNad_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8 currentNad, Std_ReturnType* result);
typedef void (* CMOCK_checkCurrentNad_CALLBACK)(uint8 currentNad, Std_ReturnType* result, int cmock_num_calls);
void checkCurrentNad_AddCallback(CMOCK_checkCurrentNad_CALLBACK Callback);
void checkCurrentNad_Stub(CMOCK_checkCurrentNad_CALLBACK Callback);
#define checkCurrentNad_StubWithCallback checkCurrentNad_Stub
#define checkMsgDataLength_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("checkMsgDataLength requires _Ignore (not AndReturn)");
#define checkMsgDataLength_Ignore() checkMsgDataLength_CMockIgnore()
void checkMsgDataLength_CMockIgnore(void);
#define checkMsgDataLength_StopIgnore() checkMsgDataLength_CMockStopIgnore()
void checkMsgDataLength_CMockStopIgnore(void);
#define checkMsgDataLength_ExpectAndReturn(dataLength, result, cmock_retval) TEST_FAIL_MESSAGE("checkMsgDataLength requires _Expect (not AndReturn)");
#define checkMsgDataLength_Expect(dataLength, result) checkMsgDataLength_CMockExpect(__LINE__, dataLength, result)
void checkMsgDataLength_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t dataLength, Std_ReturnType* result);
typedef void (* CMOCK_checkMsgDataLength_CALLBACK)(uint16_t dataLength, Std_ReturnType* result, int cmock_num_calls);
void checkMsgDataLength_AddCallback(CMOCK_checkMsgDataLength_CALLBACK Callback);
void checkMsgDataLength_Stub(CMOCK_checkMsgDataLength_CALLBACK Callback);
#define checkMsgDataLength_StubWithCallback checkMsgDataLength_Stub
#define RdbiVhitOverVoltageFaultDiag__Ignore() TEST_FAIL_MESSAGE("RdbiVhitOverVoltageFaultDiag_ requires _IgnoreAndReturn");
#define RdbiVhitOverVoltageFaultDiag__IgnoreAndReturn(cmock_retval) RdbiVhitOverVoltageFaultDiag__CMockIgnoreAndReturn(__LINE__, cmock_retval)
void RdbiVhitOverVoltageFaultDiag__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return);
#define RdbiVhitOverVoltageFaultDiag__StopIgnore() RdbiVhitOverVoltageFaultDiag__CMockStopIgnore()
void RdbiVhitOverVoltageFaultDiag__CMockStopIgnore(void);
#define RdbiVhitOverVoltageFaultDiag__Expect(output_pu8, size_pu8, errCode_pu8) TEST_FAIL_MESSAGE("RdbiVhitOverVoltageFaultDiag_ requires _ExpectAndReturn");
#define RdbiVhitOverVoltageFaultDiag__ExpectAndReturn(output_pu8, size_pu8, errCode_pu8, cmock_retval) RdbiVhitOverVoltageFaultDiag__CMockExpectAndReturn(__LINE__, output_pu8, size_pu8, errCode_pu8, cmock_retval)
void RdbiVhitOverVoltageFaultDiag__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8, Std_ReturnType cmock_to_return);
typedef Std_ReturnType (* CMOCK_RdbiVhitOverVoltageFaultDiag__CALLBACK)(uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8, int cmock_num_calls);
void RdbiVhitOverVoltageFaultDiag__AddCallback(CMOCK_RdbiVhitOverVoltageFaultDiag__CALLBACK Callback);
void RdbiVhitOverVoltageFaultDiag__Stub(CMOCK_RdbiVhitOverVoltageFaultDiag__CALLBACK Callback);
#define RdbiVhitOverVoltageFaultDiag__StubWithCallback RdbiVhitOverVoltageFaultDiag__Stub
#define SubfunctionRequestOutOfRange__Ignore() TEST_FAIL_MESSAGE("SubfunctionRequestOutOfRange_ requires _IgnoreAndReturn");
#define SubfunctionRequestOutOfRange__IgnoreAndReturn(cmock_retval) SubfunctionRequestOutOfRange__CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SubfunctionRequestOutOfRange__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return);
#define SubfunctionRequestOutOfRange__StopIgnore() SubfunctionRequestOutOfRange__CMockStopIgnore()
void SubfunctionRequestOutOfRange__CMockStopIgnore(void);
#define SubfunctionRequestOutOfRange__Expect(output_pu8, size_pu8, errCode_pu8) TEST_FAIL_MESSAGE("SubfunctionRequestOutOfRange_ requires _ExpectAndReturn");
#define SubfunctionRequestOutOfRange__ExpectAndReturn(output_pu8, size_pu8, errCode_pu8, cmock_retval) SubfunctionRequestOutOfRange__CMockExpectAndReturn(__LINE__, output_pu8, size_pu8, errCode_pu8, cmock_retval)
void SubfunctionRequestOutOfRange__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8, Std_ReturnType cmock_to_return);
typedef Std_ReturnType (* CMOCK_SubfunctionRequestOutOfRange__CALLBACK)(uint8* const output_pu8, uint8* const size_pu8, uint8* const errCode_pu8, int cmock_num_calls);
void SubfunctionRequestOutOfRange__AddCallback(CMOCK_SubfunctionRequestOutOfRange__CALLBACK Callback);
void SubfunctionRequestOutOfRange__Stub(CMOCK_SubfunctionRequestOutOfRange__CALLBACK Callback);
#define SubfunctionRequestOutOfRange__StubWithCallback SubfunctionRequestOutOfRange__Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
