/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_errorDataDetection_priv.h"

static const char* CMockString_EDD_Crc8ComputeInternal = "EDD_Crc8ComputeInternal";
static const char* CMockString_data = "data";
static const char* CMockString_length = "length";

typedef struct _CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  int CallOrder;
  const uint8_t* Expected_data;
  uint8_t Expected_length;

} CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE;

static struct mock_errorDataDetection_privInstance
{
  char EDD_Crc8ComputeInternal_IgnoreBool;
  uint8_t EDD_Crc8ComputeInternal_FinalReturn;
  char EDD_Crc8ComputeInternal_CallbackBool;
  CMOCK_EDD_Crc8ComputeInternal_CALLBACK EDD_Crc8ComputeInternal_CallbackFunctionPointer;
  int EDD_Crc8ComputeInternal_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE EDD_Crc8ComputeInternal_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_errorDataDetection_priv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.EDD_Crc8ComputeInternal_CallInstance;
  if (Mock.EDD_Crc8ComputeInternal_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_EDD_Crc8ComputeInternal);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_errorDataDetection_priv_Init(void)
{
  mock_errorDataDetection_priv_Destroy();
}

void mock_errorDataDetection_priv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

uint8_t EDD_Crc8ComputeInternal(const uint8_t* data, uint8_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_EDD_Crc8ComputeInternal);
  cmock_call_instance = (CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.EDD_Crc8ComputeInternal_CallInstance);
  Mock.EDD_Crc8ComputeInternal_CallInstance = CMock_Guts_MemNext(Mock.EDD_Crc8ComputeInternal_CallInstance);
  if (Mock.EDD_Crc8ComputeInternal_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.EDD_Crc8ComputeInternal_FinalReturn;
    Mock.EDD_Crc8ComputeInternal_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.EDD_Crc8ComputeInternal_CallbackBool &&
      Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer != NULL)
  {
    uint8_t cmock_cb_ret = Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer(data, length, Mock.EDD_Crc8ComputeInternal_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_EDD_Crc8ComputeInternal,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_EDD_Crc8ComputeInternal,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer(data, length, Mock.EDD_Crc8ComputeInternal_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_EDD_Crc8ComputeInternal(CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE* cmock_call_instance, const uint8_t* data, uint8_t length);
void CMockExpectParameters_EDD_Crc8ComputeInternal(CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE* cmock_call_instance, const uint8_t* data, uint8_t length)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_length = length;
}

void EDD_Crc8ComputeInternal_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE));
  CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE* cmock_call_instance = (CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.EDD_Crc8ComputeInternal_CallInstance = CMock_Guts_MemChain(Mock.EDD_Crc8ComputeInternal_CallInstance, cmock_guts_index);
  Mock.EDD_Crc8ComputeInternal_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.EDD_Crc8ComputeInternal_IgnoreBool = (char)1;
}

void EDD_Crc8ComputeInternal_CMockStopIgnore(void)
{
  if(Mock.EDD_Crc8ComputeInternal_IgnoreBool)
    Mock.EDD_Crc8ComputeInternal_CallInstance = CMock_Guts_MemNext(Mock.EDD_Crc8ComputeInternal_CallInstance);
  Mock.EDD_Crc8ComputeInternal_IgnoreBool = (char)0;
}

void EDD_Crc8ComputeInternal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* data, uint8_t length, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE));
  CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE* cmock_call_instance = (CMOCK_EDD_Crc8ComputeInternal_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.EDD_Crc8ComputeInternal_CallInstance = CMock_Guts_MemChain(Mock.EDD_Crc8ComputeInternal_CallInstance, cmock_guts_index);
  Mock.EDD_Crc8ComputeInternal_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_EDD_Crc8ComputeInternal(cmock_call_instance, data, length);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void EDD_Crc8ComputeInternal_AddCallback(CMOCK_EDD_Crc8ComputeInternal_CALLBACK Callback)
{
  Mock.EDD_Crc8ComputeInternal_IgnoreBool = (char)0;
  Mock.EDD_Crc8ComputeInternal_CallbackBool = (char)1;
  Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer = Callback;
}

void EDD_Crc8ComputeInternal_Stub(CMOCK_EDD_Crc8ComputeInternal_CALLBACK Callback)
{
  Mock.EDD_Crc8ComputeInternal_IgnoreBool = (char)0;
  Mock.EDD_Crc8ComputeInternal_CallbackBool = (char)0;
  Mock.EDD_Crc8ComputeInternal_CallbackFunctionPointer = Callback;
}

