/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_ERRORDATADETECTION_PRIV_H
#define _MOCK_ERRORDATADETECTION_PRIV_H

#include "unity.h"
#include "errorDataDetection_priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_errorDataDetection_priv_Init(void);
void mock_errorDataDetection_priv_Destroy(void);
void mock_errorDataDetection_priv_Verify(void);




#define EDD_Crc8ComputeInternal_Ignore() TEST_FAIL_MESSAGE("EDD_Crc8ComputeInternal requires _IgnoreAndReturn");
#define EDD_Crc8ComputeInternal_IgnoreAndReturn(cmock_retval) EDD_Crc8ComputeInternal_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void EDD_Crc8ComputeInternal_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define EDD_Crc8ComputeInternal_StopIgnore() EDD_Crc8ComputeInternal_CMockStopIgnore()
void EDD_Crc8ComputeInternal_CMockStopIgnore(void);
#define EDD_Crc8ComputeInternal_Expect(data, length) TEST_FAIL_MESSAGE("EDD_Crc8ComputeInternal requires _ExpectAndReturn");
#define EDD_Crc8ComputeInternal_ExpectAndReturn(data, length, cmock_retval) EDD_Crc8ComputeInternal_CMockExpectAndReturn(__LINE__, data, length, cmock_retval)
void EDD_Crc8ComputeInternal_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* data, uint8_t length, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_EDD_Crc8ComputeInternal_CALLBACK)(const uint8_t* data, uint8_t length, int cmock_num_calls);
void EDD_Crc8ComputeInternal_AddCallback(CMOCK_EDD_Crc8ComputeInternal_CALLBACK Callback);
void EDD_Crc8ComputeInternal_Stub(CMOCK_EDD_Crc8ComputeInternal_CALLBACK Callback);
#define EDD_Crc8ComputeInternal_StubWithCallback EDD_Crc8ComputeInternal_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
