/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "unity.h"
#include "EDD_VerifyCrc8.h"
#include "mock_errorDataDetection_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_EDD_VerifyCrc8_NullDataPointer(void);
extern void test_EDD_VerifyCrc8_NullResultPointer(void);
extern void test_EDD_VerifyCrc8_BothPointersNull(void);
extern void test_EDD_VerifyCrc8_ZeroLength(void);
extern void test_EDD_VerifyCrc8_ValidCrcMatch(void);
extern void test_EDD_VerifyCrc8_ValidCrcMismatch(void);
extern void test_EDD_VerifyCrc8_SingleByteMatch(void);
extern void test_EDD_VerifyCrc8_MaxLengthMatch(void);
extern void test_EDD_VerifyCrc8_LengthOne(void);
extern void test_EDD_VerifyCrc8_CrcZero(void);
extern void test_EDD_VerifyCrc8_CrcMaxValue(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_errorDataDetection_priv_Init();
}
static void CMock_Verify(void)
{
  mock_errorDataDetection_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_errorDataDetection_priv_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_EDD_VerifyCrc8.c");
  run_test(test_EDD_VerifyCrc8_NullDataPointer, "test_EDD_VerifyCrc8_NullDataPointer", 31);
  run_test(test_EDD_VerifyCrc8_NullResultPointer, "test_EDD_VerifyCrc8_NullResultPointer", 45);
  run_test(test_EDD_VerifyCrc8_BothPointersNull, "test_EDD_VerifyCrc8_BothPointersNull", 59);
  run_test(test_EDD_VerifyCrc8_ZeroLength, "test_EDD_VerifyCrc8_ZeroLength", 72);
  run_test(test_EDD_VerifyCrc8_ValidCrcMatch, "test_EDD_VerifyCrc8_ValidCrcMatch", 87);
  run_test(test_EDD_VerifyCrc8_ValidCrcMismatch, "test_EDD_VerifyCrc8_ValidCrcMismatch", 107);
  run_test(test_EDD_VerifyCrc8_SingleByteMatch, "test_EDD_VerifyCrc8_SingleByteMatch", 128);
  run_test(test_EDD_VerifyCrc8_MaxLengthMatch, "test_EDD_VerifyCrc8_MaxLengthMatch", 147);
  run_test(test_EDD_VerifyCrc8_LengthOne, "test_EDD_VerifyCrc8_LengthOne", 172);
  run_test(test_EDD_VerifyCrc8_CrcZero, "test_EDD_VerifyCrc8_CrcZero", 191);
  run_test(test_EDD_VerifyCrc8_CrcMaxValue, "test_EDD_VerifyCrc8_CrcMaxValue", 210);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
