@startuml inline_umlgraph_1.png
start
:Init l_ecuTemp_s16 equal to 0;
if (NtcTemp_s16 <= PAR_ECU_TEMP_LOW_THR \n   OR NtcErr_b == true) then (yes)
  :Assign SysTemp_s16 to l_ecuTemp_s16;
else (no)
  if (NtcTemp_s16 >= PAR_ECU_TEMP_UP_THR) then (yes)
    :Assign NtcTemp_s16 to l_ecuTemp_s16;
  else (no)
    :Evaluate l_ecuTemp_s16 as \n(NtcTemp_s16 * (NtcTemp_s16 - PAR_ECU_TEMP_LOW_THR)\n + SysTemp_s16 * (PAR_ECU_TEMP_UP_THR - NtcTemp_s16))\n / (PAR_ECU_TEMP_UP_THR - PAR_ECU_TEMP_LOW_THR);
    note 
      This interpolation blends the two temperature
      measurements smoothly in the middle range,
      ensuring a gradual transition between
      SysTemp_s16 (low range) and NtcTemp_s16 (high range).
    end note
  endif
endif

:return l_ecuTemp_s16;
stop
@enduml
@startuml inline_umlgraph_2.png
start
:Init l_ecuTemp_s16 equal to 0;
if (NtcTemp_s16 <= PAR_ECU_TEMP_LOW_THR \n   OR NtcErr_b == true) then (yes)
  :Assign SysTemp_s16 to l_ecuTemp_s16;
else (no)
  if (NtcTemp_s16 >= PAR_ECU_TEMP_UP_THR) then (yes)
    :Assign NtcTemp_s16 to l_ecuTemp_s16;
  else (no)
    :Evaluate l_ecuTemp_s16 as \n(NtcTemp_s16 * (NtcTemp_s16 - PAR_ECU_TEMP_LOW_THR)\n + SysTemp_s16 * (PAR_ECU_TEMP_UP_THR - NtcTemp_s16))\n / (PAR_ECU_TEMP_UP_THR - PAR_ECU_TEMP_LOW_THR);
    note 
      This interpolation blends the two temperature
      measurements smoothly in the middle range,
      ensuring a gradual transition between
      SysTemp_s16 (low range) and NtcTemp_s16 (high range).
    end note
  endif
endif

:return l_ecuTemp_s16;
stop
@enduml
