/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_VOLTMONITORING_CFG_H
#define _MOCK_VOLTMONITORING_CFG_H

#include "unity.h"
#include "VoltMonitoring_cfg.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_VoltMonitoring_cfg_Init(void);
void mock_VoltMonitoring_cfg_Destroy(void);
void mock_VoltMonitoring_cfg_Verify(void);




#define VoltMon_ReadVoltageProject_mV_Ignore() TEST_FAIL_MESSAGE("VoltMon_ReadVoltageProject_mV requires _IgnoreAndReturn");
#define VoltMon_ReadVoltageProject_mV_IgnoreAndReturn(cmock_retval) VoltMon_ReadVoltageProject_mV_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void VoltMon_ReadVoltageProject_mV_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define VoltMon_ReadVoltageProject_mV_StopIgnore() VoltMon_ReadVoltageProject_mV_CMockStopIgnore()
void VoltMon_ReadVoltageProject_mV_CMockStopIgnore(void);
#define VoltMon_ReadVoltageProject_mV_Expect() TEST_FAIL_MESSAGE("VoltMon_ReadVoltageProject_mV requires _ExpectAndReturn");
#define VoltMon_ReadVoltageProject_mV_ExpectAndReturn(cmock_retval) VoltMon_ReadVoltageProject_mV_CMockExpectAndReturn(__LINE__, cmock_retval)
void VoltMon_ReadVoltageProject_mV_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_VoltMon_ReadVoltageProject_mV_CALLBACK)(int cmock_num_calls);
void VoltMon_ReadVoltageProject_mV_AddCallback(CMOCK_VoltMon_ReadVoltageProject_mV_CALLBACK Callback);
void VoltMon_ReadVoltageProject_mV_Stub(CMOCK_VoltMon_ReadVoltageProject_mV_CALLBACK Callback);
#define VoltMon_ReadVoltageProject_mV_StubWithCallback VoltMon_ReadVoltageProject_mV_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
