/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_VoltMonitoring_cfg.h"

static const char* CMockString_VoltMon_ReadVoltageProject_mV = "VoltMon_ReadVoltageProject_mV";

typedef struct _CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  int CallOrder;

} CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE;

static struct mock_VoltMonitoring_cfgInstance
{
  char VoltMon_ReadVoltageProject_mV_IgnoreBool;
  uint16_t VoltMon_ReadVoltageProject_mV_FinalReturn;
  char VoltMon_ReadVoltageProject_mV_CallbackBool;
  CMOCK_VoltMon_ReadVoltageProject_mV_CALLBACK VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer;
  int VoltMon_ReadVoltageProject_mV_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE VoltMon_ReadVoltageProject_mV_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_VoltMonitoring_cfg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.VoltMon_ReadVoltageProject_mV_CallInstance;
  if (Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_VoltMon_ReadVoltageProject_mV);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_VoltMonitoring_cfg_Init(void)
{
  mock_VoltMonitoring_cfg_Destroy();
}

void mock_VoltMonitoring_cfg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

uint16_t VoltMon_ReadVoltageProject_mV(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_VoltMon_ReadVoltageProject_mV);
  cmock_call_instance = (CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.VoltMon_ReadVoltageProject_mV_CallInstance);
  Mock.VoltMon_ReadVoltageProject_mV_CallInstance = CMock_Guts_MemNext(Mock.VoltMon_ReadVoltageProject_mV_CallInstance);
  if (Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.VoltMon_ReadVoltageProject_mV_FinalReturn;
    Mock.VoltMon_ReadVoltageProject_mV_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.VoltMon_ReadVoltageProject_mV_CallbackBool &&
      Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer != NULL)
  {
    uint16_t cmock_cb_ret = Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer(Mock.VoltMon_ReadVoltageProject_mV_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer(Mock.VoltMon_ReadVoltageProject_mV_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void VoltMon_ReadVoltageProject_mV_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE));
  CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE* cmock_call_instance = (CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.VoltMon_ReadVoltageProject_mV_CallInstance = CMock_Guts_MemChain(Mock.VoltMon_ReadVoltageProject_mV_CallInstance, cmock_guts_index);
  Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool = (char)1;
}

void VoltMon_ReadVoltageProject_mV_CMockStopIgnore(void)
{
  if(Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool)
    Mock.VoltMon_ReadVoltageProject_mV_CallInstance = CMock_Guts_MemNext(Mock.VoltMon_ReadVoltageProject_mV_CallInstance);
  Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool = (char)0;
}

void VoltMon_ReadVoltageProject_mV_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE));
  CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE* cmock_call_instance = (CMOCK_VoltMon_ReadVoltageProject_mV_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.VoltMon_ReadVoltageProject_mV_CallInstance = CMock_Guts_MemChain(Mock.VoltMon_ReadVoltageProject_mV_CallInstance, cmock_guts_index);
  Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void VoltMon_ReadVoltageProject_mV_AddCallback(CMOCK_VoltMon_ReadVoltageProject_mV_CALLBACK Callback)
{
  Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool = (char)0;
  Mock.VoltMon_ReadVoltageProject_mV_CallbackBool = (char)1;
  Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer = Callback;
}

void VoltMon_ReadVoltageProject_mV_Stub(CMOCK_VoltMon_ReadVoltageProject_mV_CALLBACK Callback)
{
  Mock.VoltMon_ReadVoltageProject_mV_IgnoreBool = (char)0;
  Mock.VoltMon_ReadVoltageProject_mV_CallbackBool = (char)0;
  Mock.VoltMon_ReadVoltageProject_mV_CallbackFunctionPointer = Callback;
}

