/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_VOLTMONITORING_PRIV_H
#define _MOCK_VOLTMONITORING_PRIV_H

#include "unity.h"
#include "VoltMonitoring_priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_VoltMonitoring_priv_Init(void);
void mock_VoltMonitoring_priv_Destroy(void);
void mock_VoltMonitoring_priv_Verify(void);




#define VoltMon_GetUnderOn_mV_Ignore() TEST_FAIL_MESSAGE("VoltMon_GetUnderOn_mV requires _IgnoreAndReturn");
#define VoltMon_GetUnderOn_mV_IgnoreAndReturn(cmock_retval) VoltMon_GetUnderOn_mV_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void VoltMon_GetUnderOn_mV_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define VoltMon_GetUnderOn_mV_StopIgnore() VoltMon_GetUnderOn_mV_CMockStopIgnore()
void VoltMon_GetUnderOn_mV_CMockStopIgnore(void);
#define VoltMon_GetUnderOn_mV_Expect() TEST_FAIL_MESSAGE("VoltMon_GetUnderOn_mV requires _ExpectAndReturn");
#define VoltMon_GetUnderOn_mV_ExpectAndReturn(cmock_retval) VoltMon_GetUnderOn_mV_CMockExpectAndReturn(__LINE__, cmock_retval)
void VoltMon_GetUnderOn_mV_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_VoltMon_GetUnderOn_mV_CALLBACK)(int cmock_num_calls);
void VoltMon_GetUnderOn_mV_AddCallback(CMOCK_VoltMon_GetUnderOn_mV_CALLBACK Callback);
void VoltMon_GetUnderOn_mV_Stub(CMOCK_VoltMon_GetUnderOn_mV_CALLBACK Callback);
#define VoltMon_GetUnderOn_mV_StubWithCallback VoltMon_GetUnderOn_mV_Stub
#define VoltMon_GetUnderOff_mV_Ignore() TEST_FAIL_MESSAGE("VoltMon_GetUnderOff_mV requires _IgnoreAndReturn");
#define VoltMon_GetUnderOff_mV_IgnoreAndReturn(cmock_retval) VoltMon_GetUnderOff_mV_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void VoltMon_GetUnderOff_mV_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define VoltMon_GetUnderOff_mV_StopIgnore() VoltMon_GetUnderOff_mV_CMockStopIgnore()
void VoltMon_GetUnderOff_mV_CMockStopIgnore(void);
#define VoltMon_GetUnderOff_mV_Expect() TEST_FAIL_MESSAGE("VoltMon_GetUnderOff_mV requires _ExpectAndReturn");
#define VoltMon_GetUnderOff_mV_ExpectAndReturn(cmock_retval) VoltMon_GetUnderOff_mV_CMockExpectAndReturn(__LINE__, cmock_retval)
void VoltMon_GetUnderOff_mV_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_VoltMon_GetUnderOff_mV_CALLBACK)(int cmock_num_calls);
void VoltMon_GetUnderOff_mV_AddCallback(CMOCK_VoltMon_GetUnderOff_mV_CALLBACK Callback);
void VoltMon_GetUnderOff_mV_Stub(CMOCK_VoltMon_GetUnderOff_mV_CALLBACK Callback);
#define VoltMon_GetUnderOff_mV_StubWithCallback VoltMon_GetUnderOff_mV_Stub
#define VoltMon_GetOverOn_mV_Ignore() TEST_FAIL_MESSAGE("VoltMon_GetOverOn_mV requires _IgnoreAndReturn");
#define VoltMon_GetOverOn_mV_IgnoreAndReturn(cmock_retval) VoltMon_GetOverOn_mV_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void VoltMon_GetOverOn_mV_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define VoltMon_GetOverOn_mV_StopIgnore() VoltMon_GetOverOn_mV_CMockStopIgnore()
void VoltMon_GetOverOn_mV_CMockStopIgnore(void);
#define VoltMon_GetOverOn_mV_Expect() TEST_FAIL_MESSAGE("VoltMon_GetOverOn_mV requires _ExpectAndReturn");
#define VoltMon_GetOverOn_mV_ExpectAndReturn(cmock_retval) VoltMon_GetOverOn_mV_CMockExpectAndReturn(__LINE__, cmock_retval)
void VoltMon_GetOverOn_mV_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_VoltMon_GetOverOn_mV_CALLBACK)(int cmock_num_calls);
void VoltMon_GetOverOn_mV_AddCallback(CMOCK_VoltMon_GetOverOn_mV_CALLBACK Callback);
void VoltMon_GetOverOn_mV_Stub(CMOCK_VoltMon_GetOverOn_mV_CALLBACK Callback);
#define VoltMon_GetOverOn_mV_StubWithCallback VoltMon_GetOverOn_mV_Stub
#define VoltMon_GetOverOff_mV_Ignore() TEST_FAIL_MESSAGE("VoltMon_GetOverOff_mV requires _IgnoreAndReturn");
#define VoltMon_GetOverOff_mV_IgnoreAndReturn(cmock_retval) VoltMon_GetOverOff_mV_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void VoltMon_GetOverOff_mV_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
#define VoltMon_GetOverOff_mV_StopIgnore() VoltMon_GetOverOff_mV_CMockStopIgnore()
void VoltMon_GetOverOff_mV_CMockStopIgnore(void);
#define VoltMon_GetOverOff_mV_Expect() TEST_FAIL_MESSAGE("VoltMon_GetOverOff_mV requires _ExpectAndReturn");
#define VoltMon_GetOverOff_mV_ExpectAndReturn(cmock_retval) VoltMon_GetOverOff_mV_CMockExpectAndReturn(__LINE__, cmock_retval)
void VoltMon_GetOverOff_mV_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return);
typedef uint16_t (* CMOCK_VoltMon_GetOverOff_mV_CALLBACK)(int cmock_num_calls);
void VoltMon_GetOverOff_mV_AddCallback(CMOCK_VoltMon_GetOverOff_mV_CALLBACK Callback);
void VoltMon_GetOverOff_mV_Stub(CMOCK_VoltMon_GetOverOff_mV_CALLBACK Callback);
#define VoltMon_GetOverOff_mV_StubWithCallback VoltMon_GetOverOff_mV_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
