@startuml inline_umlgraph_1.png
start

:Init l_vbat_u16 equal to the value returned by VoltMeas_get_vbat_u16()
Init l_tecu_s16 equal to the value returned by TempMeas_get_filtEcuTemp_s16();

:Assign IdcVdc the value returned by CurrentMon_SetDeratingLimits_s16(l_vbat_u16,  CurrentMon_IdcVdcTab,CURRENTMON_IDC_VDC_N_POINTS)
Assign IdcTemp the value returned by CurrentMon_SetDeratingLimits_s16(l_tecu_s16,  CurrentMon_IdcTecuTab,CURRENTMON_IDC_TECU_N_POINTS)
Assign IlineTemp the value returned by CurrentMon_SetDeratingLimits_s16(l_tecu_s16,  CurrentMon_IlineTecuTab,CURRENTMON_ILINE_TECU_N_POINTS)
Assign to IdcLim_s16 the min between l_limitIdcVdc_s16 and l_limitIdctemp_s16;

stop
@enduml
