/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "unity.h"
#include "voltMonRun.h"
#include "mock_VoltMonitoring_priv.h"
#include "mock_VoltMonitoring_cfg.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_voltMonRun_NormalState_VoltageWithinBand_RemainsNormal(void);
extern void test_voltMonRun_NormalState_VoltageToUnderVoltage(void);
extern void test_voltMonRun_NormalState_VoltageToOverVoltage(void);
extern void test_voltMonRun_UnderVoltageState_VoltageRecoveryToNormal(void);
extern void test_voltMonRun_UnderVoltageState_VoltageStaysUnderVoltage(void);
extern void test_voltMonRun_UnderVoltageState_PartialRecovery_ResetTimer(void);
extern void test_voltMonRun_OverVoltageState_VoltageRecoveryToNormal(void);
extern void test_voltMonRun_NormalState_UnderVoltageDebouncing_IncompleteTimer(void);
extern void test_voltMonRun_NormalState_OverVoltageDebouncing_IncompleteTimer(void);
extern void test_voltMonRun_NormalState_VoltageOscillation_NoTransition(void);
extern void test_voltMonRun_Hysteresis_UnderVoltage_OffThreshold(void);
extern void test_voltMonRun_Hysteresis_OverVoltage_OffThreshold(void);
extern void test_voltMonRun_CyclicTransitions_NORMAL_UV_NORMAL(void);
extern void test_voltMonRun_CyclicTransitions_NORMAL_OV_NORMAL(void);
extern void test_voltMonRun_LongDurationUnderVoltage(void);
extern void test_voltMonRun_LongDurationOverVoltage(void);
extern void test_voltMonRun_BoundaryVoltage_JustBelowUnderOn(void);
extern void test_voltMonRun_BoundaryVoltage_JustAboveOverOn(void);
extern void test_voltMonRun_ZeroVoltage(void);
extern void test_voltMonRun_VeryHighVoltage(void);
extern void test_voltMonRun_TimerOverflow_LongElapsedTime(void);
extern void test_voltMonRun_AlternatingStates_NORMAL_UV_OV_NORMAL(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_VoltMonitoring_priv_Init();
  mock_VoltMonitoring_cfg_Init();
}
static void CMock_Verify(void)
{
  mock_VoltMonitoring_priv_Verify();
  mock_VoltMonitoring_cfg_Verify();
}
static void CMock_Destroy(void)
{
  mock_VoltMonitoring_priv_Destroy();
  mock_VoltMonitoring_cfg_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_voltMonRun.c");
  run_test(test_voltMonRun_NormalState_VoltageWithinBand_RemainsNormal, "test_voltMonRun_NormalState_VoltageWithinBand_RemainsNormal", 40);
  run_test(test_voltMonRun_NormalState_VoltageToUnderVoltage, "test_voltMonRun_NormalState_VoltageToUnderVoltage", 64);
  run_test(test_voltMonRun_NormalState_VoltageToOverVoltage, "test_voltMonRun_NormalState_VoltageToOverVoltage", 91);
  run_test(test_voltMonRun_UnderVoltageState_VoltageRecoveryToNormal, "test_voltMonRun_UnderVoltageState_VoltageRecoveryToNormal", 122);
  run_test(test_voltMonRun_UnderVoltageState_VoltageStaysUnderVoltage, "test_voltMonRun_UnderVoltageState_VoltageStaysUnderVoltage", 160);
  run_test(test_voltMonRun_UnderVoltageState_PartialRecovery_ResetTimer, "test_voltMonRun_UnderVoltageState_PartialRecovery_ResetTimer", 198);
  run_test(test_voltMonRun_OverVoltageState_VoltageRecoveryToNormal, "test_voltMonRun_OverVoltageState_VoltageRecoveryToNormal", 249);
  run_test(test_voltMonRun_NormalState_UnderVoltageDebouncing_IncompleteTimer, "test_voltMonRun_NormalState_UnderVoltageDebouncing_IncompleteTimer", 291);
  run_test(test_voltMonRun_NormalState_OverVoltageDebouncing_IncompleteTimer, "test_voltMonRun_NormalState_OverVoltageDebouncing_IncompleteTimer", 314);
  run_test(test_voltMonRun_NormalState_VoltageOscillation_NoTransition, "test_voltMonRun_NormalState_VoltageOscillation_NoTransition", 337);
  run_test(test_voltMonRun_Hysteresis_UnderVoltage_OffThreshold, "test_voltMonRun_Hysteresis_UnderVoltage_OffThreshold", 372);
  run_test(test_voltMonRun_Hysteresis_OverVoltage_OffThreshold, "test_voltMonRun_Hysteresis_OverVoltage_OffThreshold", 409);
  run_test(test_voltMonRun_CyclicTransitions_NORMAL_UV_NORMAL, "test_voltMonRun_CyclicTransitions_NORMAL_UV_NORMAL", 450);
  run_test(test_voltMonRun_CyclicTransitions_NORMAL_OV_NORMAL, "test_voltMonRun_CyclicTransitions_NORMAL_OV_NORMAL", 491);
  run_test(test_voltMonRun_LongDurationUnderVoltage, "test_voltMonRun_LongDurationUnderVoltage", 532);
  run_test(test_voltMonRun_LongDurationOverVoltage, "test_voltMonRun_LongDurationOverVoltage", 556);
  run_test(test_voltMonRun_BoundaryVoltage_JustBelowUnderOn, "test_voltMonRun_BoundaryVoltage_JustBelowUnderOn", 580);
  run_test(test_voltMonRun_BoundaryVoltage_JustAboveOverOn, "test_voltMonRun_BoundaryVoltage_JustAboveOverOn", 603);
  run_test(test_voltMonRun_ZeroVoltage, "test_voltMonRun_ZeroVoltage", 626);
  run_test(test_voltMonRun_VeryHighVoltage, "test_voltMonRun_VeryHighVoltage", 649);
  run_test(test_voltMonRun_TimerOverflow_LongElapsedTime, "test_voltMonRun_TimerOverflow_LongElapsedTime", 672);
  run_test(test_voltMonRun_AlternatingStates_NORMAL_UV_OV_NORMAL, "test_voltMonRun_AlternatingStates_NORMAL_UV_OV_NORMAL", 692);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
