/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "unity.h"
#include "checkCurrentNad.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_checkCurrentNad_WithInvalidNad_0x7F_ReturnsNotOk(void);
extern void test_checkCurrentNad_WithInvalidNad_0x7E_ReturnsNotOk(void);
extern void test_checkCurrentNad_WithValidNad_0x00_ReturnsOk(void);
extern void test_checkCurrentNad_WithValidNad_0x01_ReturnsOk(void);
extern void test_checkCurrentNad_WithValidNad_0x7D_ReturnsOk(void);
extern void test_checkCurrentNad_WithValidNad_0xFF_ReturnsOk(void);
extern void test_checkCurrentNad_WithValidNad_0x80_ReturnsOk(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_checkCurrentNad.c");
  run_test(test_checkCurrentNad_WithInvalidNad_0x7F_ReturnsNotOk, "test_checkCurrentNad_WithInvalidNad_0x7F_ReturnsNotOk", 18);
  run_test(test_checkCurrentNad_WithInvalidNad_0x7E_ReturnsNotOk, "test_checkCurrentNad_WithInvalidNad_0x7E_ReturnsNotOk", 31);
  run_test(test_checkCurrentNad_WithValidNad_0x00_ReturnsOk, "test_checkCurrentNad_WithValidNad_0x00_ReturnsOk", 44);
  run_test(test_checkCurrentNad_WithValidNad_0x01_ReturnsOk, "test_checkCurrentNad_WithValidNad_0x01_ReturnsOk", 57);
  run_test(test_checkCurrentNad_WithValidNad_0x7D_ReturnsOk, "test_checkCurrentNad_WithValidNad_0x7D_ReturnsOk", 70);
  run_test(test_checkCurrentNad_WithValidNad_0xFF_ReturnsOk, "test_checkCurrentNad_WithValidNad_0xFF_ReturnsOk", 83);
  run_test(test_checkCurrentNad_WithValidNad_0x80_ReturnsOk, "test_checkCurrentNad_WithValidNad_0x80_ReturnsOk", 96);

  return UNITY_END();
}
