/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_diagnostic_cfg.h"

static const char* CMockString_checkCurrentNad = "checkCurrentNad";
static const char* CMockString_checkMsgDataLength = "checkMsgDataLength";
static const char* CMockString_currentNad = "currentNad";
static const char* CMockString_dataLength = "dataLength";
static const char* CMockString_getHandlersForReadDataById = "getHandlersForReadDataById";
static const char* CMockString_l_diagBufSize_u8 = "l_diagBufSize_u8";
static const char* CMockString_l_diagBuf_pu8 = "l_diagBuf_pu8";
static const char* CMockString_l_didSupported_ = "l_didSupported_";
static const char* CMockString_l_did_cu16 = "l_did_cu16";
static const char* CMockString_l_did_u8 = "l_did_u8";
static const char* CMockString_result = "result";

typedef struct _CMOCK_checkCurrentNad_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint8 Expected_currentNad;
  Std_ReturnType* Expected_result;

} CMOCK_checkCurrentNad_CALL_INSTANCE;

typedef struct _CMOCK_checkMsgDataLength_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int CallOrder;
  uint16_t Expected_dataLength;
  Std_ReturnType* Expected_result;

} CMOCK_checkMsgDataLength_CALL_INSTANCE;

typedef struct _CMOCK_getHandlersForReadDataById_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  Std_ReturnType ReturnVal;
  int CallOrder;
  uint8 Expected_l_did_u8;
  uint16 Expected_l_did_cu16;
  uint8* Expected_l_diagBufSize_u8;
  Std_ReturnType* Expected_l_didSupported_;
  uint8* Expected_l_diagBuf_pu8;

} CMOCK_getHandlersForReadDataById_CALL_INSTANCE;

static struct mock_diagnostic_cfgInstance
{
  char checkCurrentNad_IgnoreBool;
  char checkCurrentNad_CallbackBool;
  CMOCK_checkCurrentNad_CALLBACK checkCurrentNad_CallbackFunctionPointer;
  int checkCurrentNad_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE checkCurrentNad_CallInstance;
  char checkMsgDataLength_IgnoreBool;
  char checkMsgDataLength_CallbackBool;
  CMOCK_checkMsgDataLength_CALLBACK checkMsgDataLength_CallbackFunctionPointer;
  int checkMsgDataLength_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE checkMsgDataLength_CallInstance;
  char getHandlersForReadDataById_IgnoreBool;
  Std_ReturnType getHandlersForReadDataById_FinalReturn;
  char getHandlersForReadDataById_CallbackBool;
  CMOCK_getHandlersForReadDataById_CALLBACK getHandlersForReadDataById_CallbackFunctionPointer;
  int getHandlersForReadDataById_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE getHandlersForReadDataById_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_diagnostic_cfg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.checkCurrentNad_CallInstance;
  if (Mock.checkCurrentNad_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_checkCurrentNad);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.checkCurrentNad_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.checkMsgDataLength_CallInstance;
  if (Mock.checkMsgDataLength_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_checkMsgDataLength);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.checkMsgDataLength_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.getHandlersForReadDataById_CallInstance;
  if (Mock.getHandlersForReadDataById_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_getHandlersForReadDataById);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.getHandlersForReadDataById_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_diagnostic_cfg_Init(void)
{
  mock_diagnostic_cfg_Destroy();
}

void mock_diagnostic_cfg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void checkCurrentNad(uint8 currentNad, Std_ReturnType* result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_checkCurrentNad);
  cmock_call_instance = (CMOCK_checkCurrentNad_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.checkCurrentNad_CallInstance);
  Mock.checkCurrentNad_CallInstance = CMock_Guts_MemNext(Mock.checkCurrentNad_CallInstance);
  if (Mock.checkCurrentNad_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.checkCurrentNad_CallbackBool &&
      Mock.checkCurrentNad_CallbackFunctionPointer != NULL)
  {
    Mock.checkCurrentNad_CallbackFunctionPointer(currentNad, result, Mock.checkCurrentNad_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_checkCurrentNad,CMockString_currentNad);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_currentNad, currentNad, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_checkCurrentNad,CMockString_result);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_result), (void*)(result), sizeof(Std_ReturnType), cmock_line, CMockStringMismatch);
  }
  if (Mock.checkCurrentNad_CallbackFunctionPointer != NULL)
  {
    Mock.checkCurrentNad_CallbackFunctionPointer(currentNad, result, Mock.checkCurrentNad_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_checkCurrentNad(CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance, uint8 currentNad, Std_ReturnType* result);
void CMockExpectParameters_checkCurrentNad(CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance, uint8 currentNad, Std_ReturnType* result)
{
  cmock_call_instance->Expected_currentNad = currentNad;
  cmock_call_instance->Expected_result = result;
}

void checkCurrentNad_CMockIgnore(void)
{
  Mock.checkCurrentNad_IgnoreBool = (char)1;
}

void checkCurrentNad_CMockStopIgnore(void)
{
  Mock.checkCurrentNad_IgnoreBool = (char)0;
}

void checkCurrentNad_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8 currentNad, Std_ReturnType* result)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_checkCurrentNad_CALL_INSTANCE));
  CMOCK_checkCurrentNad_CALL_INSTANCE* cmock_call_instance = (CMOCK_checkCurrentNad_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.checkCurrentNad_CallInstance = CMock_Guts_MemChain(Mock.checkCurrentNad_CallInstance, cmock_guts_index);
  Mock.checkCurrentNad_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_checkCurrentNad(cmock_call_instance, currentNad, result);
}

void checkCurrentNad_AddCallback(CMOCK_checkCurrentNad_CALLBACK Callback)
{
  Mock.checkCurrentNad_IgnoreBool = (char)0;
  Mock.checkCurrentNad_CallbackBool = (char)1;
  Mock.checkCurrentNad_CallbackFunctionPointer = Callback;
}

void checkCurrentNad_Stub(CMOCK_checkCurrentNad_CALLBACK Callback)
{
  Mock.checkCurrentNad_IgnoreBool = (char)0;
  Mock.checkCurrentNad_CallbackBool = (char)0;
  Mock.checkCurrentNad_CallbackFunctionPointer = Callback;
}

void checkMsgDataLength(uint16_t dataLength, Std_ReturnType* result)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_checkMsgDataLength);
  cmock_call_instance = (CMOCK_checkMsgDataLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.checkMsgDataLength_CallInstance);
  Mock.checkMsgDataLength_CallInstance = CMock_Guts_MemNext(Mock.checkMsgDataLength_CallInstance);
  if (Mock.checkMsgDataLength_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.checkMsgDataLength_CallbackBool &&
      Mock.checkMsgDataLength_CallbackFunctionPointer != NULL)
  {
    Mock.checkMsgDataLength_CallbackFunctionPointer(dataLength, result, Mock.checkMsgDataLength_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_checkMsgDataLength,CMockString_dataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_dataLength, dataLength, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_checkMsgDataLength,CMockString_result);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_result), (void*)(result), sizeof(Std_ReturnType), cmock_line, CMockStringMismatch);
  }
  if (Mock.checkMsgDataLength_CallbackFunctionPointer != NULL)
  {
    Mock.checkMsgDataLength_CallbackFunctionPointer(dataLength, result, Mock.checkMsgDataLength_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_checkMsgDataLength(CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance, uint16_t dataLength, Std_ReturnType* result);
void CMockExpectParameters_checkMsgDataLength(CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance, uint16_t dataLength, Std_ReturnType* result)
{
  cmock_call_instance->Expected_dataLength = dataLength;
  cmock_call_instance->Expected_result = result;
}

void checkMsgDataLength_CMockIgnore(void)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)1;
}

void checkMsgDataLength_CMockStopIgnore(void)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
}

void checkMsgDataLength_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t dataLength, Std_ReturnType* result)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_checkMsgDataLength_CALL_INSTANCE));
  CMOCK_checkMsgDataLength_CALL_INSTANCE* cmock_call_instance = (CMOCK_checkMsgDataLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.checkMsgDataLength_CallInstance = CMock_Guts_MemChain(Mock.checkMsgDataLength_CallInstance, cmock_guts_index);
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_checkMsgDataLength(cmock_call_instance, dataLength, result);
}

void checkMsgDataLength_AddCallback(CMOCK_checkMsgDataLength_CALLBACK Callback)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
  Mock.checkMsgDataLength_CallbackBool = (char)1;
  Mock.checkMsgDataLength_CallbackFunctionPointer = Callback;
}

void checkMsgDataLength_Stub(CMOCK_checkMsgDataLength_CALLBACK Callback)
{
  Mock.checkMsgDataLength_IgnoreBool = (char)0;
  Mock.checkMsgDataLength_CallbackBool = (char)0;
  Mock.checkMsgDataLength_CallbackFunctionPointer = Callback;
}

Std_ReturnType getHandlersForReadDataById(uint8 l_did_u8, uint16 l_did_cu16, uint8* l_diagBufSize_u8, Std_ReturnType* l_didSupported_, uint8* l_diagBuf_pu8)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getHandlersForReadDataById_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getHandlersForReadDataById);
  cmock_call_instance = (CMOCK_getHandlersForReadDataById_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getHandlersForReadDataById_CallInstance);
  Mock.getHandlersForReadDataById_CallInstance = CMock_Guts_MemNext(Mock.getHandlersForReadDataById_CallInstance);
  if (Mock.getHandlersForReadDataById_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.getHandlersForReadDataById_FinalReturn;
    memcpy((void*)(&Mock.getHandlersForReadDataById_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(Std_ReturnType[sizeof(cmock_call_instance->ReturnVal) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.getHandlersForReadDataById_CallbackBool &&
      Mock.getHandlersForReadDataById_CallbackFunctionPointer != NULL)
  {
    Std_ReturnType cmock_cb_ret = Mock.getHandlersForReadDataById_CallbackFunctionPointer(l_did_u8, l_did_cu16, l_diagBufSize_u8, l_didSupported_, l_diagBuf_pu8, Mock.getHandlersForReadDataById_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_getHandlersForReadDataById,CMockString_l_did_u8);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_l_did_u8, l_did_u8, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getHandlersForReadDataById,CMockString_l_did_cu16);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_l_did_cu16, l_did_cu16, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getHandlersForReadDataById,CMockString_l_diagBufSize_u8);
    if (cmock_call_instance->Expected_l_diagBufSize_u8 == NULL)
      { UNITY_TEST_ASSERT_NULL(l_diagBufSize_u8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_l_diagBufSize_u8, l_diagBufSize_u8, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_getHandlersForReadDataById,CMockString_l_didSupported_);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_l_didSupported_), (void*)(l_didSupported_), sizeof(Std_ReturnType), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_getHandlersForReadDataById,CMockString_l_diagBuf_pu8);
    if (cmock_call_instance->Expected_l_diagBuf_pu8 == NULL)
      { UNITY_TEST_ASSERT_NULL(l_diagBuf_pu8, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_l_diagBuf_pu8, l_diagBuf_pu8, 1, cmock_line, CMockStringMismatch); }
  }
  if (Mock.getHandlersForReadDataById_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.getHandlersForReadDataById_CallbackFunctionPointer(l_did_u8, l_did_cu16, l_diagBufSize_u8, l_didSupported_, l_diagBuf_pu8, Mock.getHandlersForReadDataById_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_getHandlersForReadDataById(CMOCK_getHandlersForReadDataById_CALL_INSTANCE* cmock_call_instance, uint8 l_did_u8, uint16 l_did_cu16, uint8* l_diagBufSize_u8, Std_ReturnType* l_didSupported_, uint8* l_diagBuf_pu8);
void CMockExpectParameters_getHandlersForReadDataById(CMOCK_getHandlersForReadDataById_CALL_INSTANCE* cmock_call_instance, uint8 l_did_u8, uint16 l_did_cu16, uint8* l_diagBufSize_u8, Std_ReturnType* l_didSupported_, uint8* l_diagBuf_pu8)
{
  cmock_call_instance->Expected_l_did_u8 = l_did_u8;
  cmock_call_instance->Expected_l_did_cu16 = l_did_cu16;
  cmock_call_instance->Expected_l_diagBufSize_u8 = l_diagBufSize_u8;
  cmock_call_instance->Expected_l_didSupported_ = l_didSupported_;
  cmock_call_instance->Expected_l_diagBuf_pu8 = l_diagBuf_pu8;
}

void getHandlersForReadDataById_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getHandlersForReadDataById_CALL_INSTANCE));
  CMOCK_getHandlersForReadDataById_CALL_INSTANCE* cmock_call_instance = (CMOCK_getHandlersForReadDataById_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getHandlersForReadDataById_CallInstance = CMock_Guts_MemChain(Mock.getHandlersForReadDataById_CallInstance, cmock_guts_index);
  Mock.getHandlersForReadDataById_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.getHandlersForReadDataById_IgnoreBool = (char)1;
}

void getHandlersForReadDataById_CMockStopIgnore(void)
{
  if(Mock.getHandlersForReadDataById_IgnoreBool)
    Mock.getHandlersForReadDataById_CallInstance = CMock_Guts_MemNext(Mock.getHandlersForReadDataById_CallInstance);
  Mock.getHandlersForReadDataById_IgnoreBool = (char)0;
}

void getHandlersForReadDataById_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8 l_did_u8, uint16 l_did_cu16, uint8* l_diagBufSize_u8, Std_ReturnType* l_didSupported_, uint8* l_diagBuf_pu8, Std_ReturnType cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getHandlersForReadDataById_CALL_INSTANCE));
  CMOCK_getHandlersForReadDataById_CALL_INSTANCE* cmock_call_instance = (CMOCK_getHandlersForReadDataById_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getHandlersForReadDataById_CallInstance = CMock_Guts_MemChain(Mock.getHandlersForReadDataById_CallInstance, cmock_guts_index);
  Mock.getHandlersForReadDataById_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_getHandlersForReadDataById(cmock_call_instance, l_did_u8, l_did_cu16, l_diagBufSize_u8, l_didSupported_, l_diagBuf_pu8);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(Std_ReturnType[sizeof(cmock_to_return) == sizeof(Std_ReturnType) ? 1 : -1])); /* add Std_ReturnType to :treat_as_array if this causes an error */
}

void getHandlersForReadDataById_AddCallback(CMOCK_getHandlersForReadDataById_CALLBACK Callback)
{
  Mock.getHandlersForReadDataById_IgnoreBool = (char)0;
  Mock.getHandlersForReadDataById_CallbackBool = (char)1;
  Mock.getHandlersForReadDataById_CallbackFunctionPointer = Callback;
}

void getHandlersForReadDataById_Stub(CMOCK_getHandlersForReadDataById_CALLBACK Callback)
{
  Mock.getHandlersForReadDataById_IgnoreBool = (char)0;
  Mock.getHandlersForReadDataById_CallbackBool = (char)0;
  Mock.getHandlersForReadDataById_CallbackFunctionPointer = Callback;
}

