/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_DIAGNOSTIC_PRIV_H
#define _MOCK_DIAGNOSTIC_PRIV_H

#include "unity.h"
#include "diagnostic_priv.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_diagnostic_priv_Init(void);
void mock_diagnostic_priv_Destroy(void);
void mock_diagnostic_priv_Verify(void);




#define LinDiagSendPosResponse_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("LinDiagSendPosResponse requires _Ignore (not AndReturn)");
#define LinDiagSendPosResponse_Ignore() LinDiagSendPosResponse_CMockIgnore()
void LinDiagSendPosResponse_CMockIgnore(void);
#define LinDiagSendPosResponse_StopIgnore() LinDiagSendPosResponse_CMockStopIgnore()
void LinDiagSendPosResponse_CMockStopIgnore(void);
#define LinDiagSendPosResponse_ExpectAndReturn(cmock_retval) TEST_FAIL_MESSAGE("LinDiagSendPosResponse requires _Expect (not AndReturn)");
#define LinDiagSendPosResponse_Expect() LinDiagSendPosResponse_CMockExpect(__LINE__)
void LinDiagSendPosResponse_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_LinDiagSendPosResponse_CALLBACK)(int cmock_num_calls);
void LinDiagSendPosResponse_AddCallback(CMOCK_LinDiagSendPosResponse_CALLBACK Callback);
void LinDiagSendPosResponse_Stub(CMOCK_LinDiagSendPosResponse_CALLBACK Callback);
#define LinDiagSendPosResponse_StubWithCallback LinDiagSendPosResponse_Stub
#define LinDiagSendNegResponse_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("LinDiagSendNegResponse requires _Ignore (not AndReturn)");
#define LinDiagSendNegResponse_Ignore() LinDiagSendNegResponse_CMockIgnore()
void LinDiagSendNegResponse_CMockIgnore(void);
#define LinDiagSendNegResponse_StopIgnore() LinDiagSendNegResponse_CMockStopIgnore()
void LinDiagSendNegResponse_CMockStopIgnore(void);
#define LinDiagSendNegResponse_ExpectAndReturn(errorCode, cmock_retval) TEST_FAIL_MESSAGE("LinDiagSendNegResponse requires _Expect (not AndReturn)");
#define LinDiagSendNegResponse_Expect(errorCode) LinDiagSendNegResponse_CMockExpect(__LINE__, errorCode)
void LinDiagSendNegResponse_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t errorCode);
typedef void (* CMOCK_LinDiagSendNegResponse_CALLBACK)(uint8_t errorCode, int cmock_num_calls);
void LinDiagSendNegResponse_AddCallback(CMOCK_LinDiagSendNegResponse_CALLBACK Callback);
void LinDiagSendNegResponse_Stub(CMOCK_LinDiagSendNegResponse_CALLBACK Callback);
#define LinDiagSendNegResponse_StubWithCallback LinDiagSendNegResponse_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
