@startuml inline_umlgraph_1.png
 start

 :Init l_nvmPage_ equal to NvmBlock_[dataToWrite_].belongPage_ 
 Init l_pageAddress_u32 equal to NvmPageCopy_[l_nvmPage_].startAddrPage_u32 
 Init l_blockStartAddress_u32 equal to NvmBlock_[dataToWrite_].addrData_u32 
 Init l_relOffset_u32 equal to l_blockStartAddress_u32 - l_pageAddress_u32 
 Init l_len_u8 = NvmBlock_[dataToWrite_].datal_len_u8_u8;

 :Assign true to NvmPageCopy_[l_nvmPage_].writeReq_b \n
 Assign false to NvmPageCopy_[l_nvmPage_].writingDone_b \n
 Write l_len_u8 bytes of data_pu8 inside NvmPageCopy_[l_nvmPage_].pageCopy_u8[] starting from the position l_relOffset_u32;
 if (0xFF is equal to NvmPageCopy_[l_nvmPage_].posListFifo_u8) then (yes)
  :Assign next available FIFO slot to the page \n
  Assign fifoPrelation_u8 to posListFifo_u8 \n
  Assign fifoPrelation_u8++ to fifoPrelation_u8;
 endif

 stop
@enduml
