@startuml inline_umlgraph_1.png
 start
 
 :Init l_tempEcu_s16 = TempMeas_get_filtEcuTemp_s16();
 
 if (l_tempEcu_s16 >= TEMPMON_OVERTEMP_UPTH) then (yes)
   if (EC_Get_error_overtemperature_State_e() == EFS_TRUE) then (yes)
     :Assign 0 to count_u8;
   else (no)
     :Assign count_u8++ to count_u8;
     if (count_u8 > COUNT_500MS) then (yes)
       :Assign 0 to count_u8
       Call EC_Set_error_overtemperature_State_e(EFS_TRUE);
     endif
   endif
 else (no)
   if (EC_Get_error_overtemperature_State_e() == EFS_TRUE) then (yes)
     :Assign count_u8++ to count_u8;
     if (count_u8 > COUNT_500MS) then (yes)
       :Assign 0 to count_u8
        Call EC_Set_error_overtemperature_State_e(EFS_FALSE);
     endif
   else (no)
     :Assign 0 to count_u8;
   endif
 endif
 
 stop
@enduml
